{% set name = "pytype" %}
{% set version = "2023.03.02" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/google/pytype/archive/refs/tags/{{ version }}.tar.gz
    sha256: c56fd93cf2e515855835b0058a1afe1c4436b2145b7ff9244250cb3843b6ccc0
    patches:
      - patches/patch-ninja-exe.patch
      - patches/remove-ninja-req.patch

  - url: https://github.com/google/googletest/archive/e82d320.tar.gz
    sha256: 7acdbac36f80ca68126c9112cf1e60132372aff81db7a14f08cb49e6e00af536
    folder: googletest
  - url: https://github.com/pybind/pybind11/archive/c16da99.tar.gz
    sha256: c90ada3976e1e261c49e14e18cec7645f7a744408bb258e60f0accc0171f0948
    folder: pybind11
  - url: https://github.com/python/typeshed/archive/3b6a52b.tar.gz
    sha256: 1faa985b1f73527e4472f5f03c3a67466674418b1c2c9425202ddaca84721e19
    folder: typeshed

build:
  number: 0
  skip: true  # [win]
  # no windows builds here: https://pypi.org/project/pytype/#files
  entry_points:
    - annotate-ast = pytype.tools.annotate_ast.main:main
    - merge-pyi = pytype.tools.merge_pyi.main:main
    - pytd = pytype.pytd.main:main
    - pytype = pytype.tools.analyze_project.main:main
    - pytype-single = pytype.single:main
    - pyxref = pytype.tools.xref.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - attrs >=21.4.0
    - importlab >=0.8
    - jinja2 >=3.1.2
    - libcst >=0.4.9
    - networkx <2.8.4
    - ninja >=1.10.0.post2
    - pydot >=1.4.2
    - python
    - tabulate >=0.8.10
    - toml >=0.10.2
    - typing-extensions >=4.3.0

test:
  imports:
    - pytype
    - pytype.overlays
  files:
    - run_pytype.py
  commands:
    - annotate-ast --help
    - merge-pyi --help
    - pytd --help
    - pytype --help
    - pytype-single --help
    - pyxref --help
    - python run_pytype.py # checks that pytype can actually run with a file input.
    - pip check
  requires:
    - pip

about:
  home: https://google.github.io/pytype/
  summary: Python type inferencer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
    - marcelotrevisani
    - anthchirp
