{% set name = "pytype" %}
{% set version = "2021.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 911ecff76f5febb5f6ba03c1b217eb5b79078b97a33b6e0aadf2e34f1d5a703e

build:
  number: 0
  skip: true  # [py>=39 or py2k]
  entry_points:
    - annotate-ast = pytype.tools.annotate_ast.main:main
    - merge-pyi = pytype.tools.merge_pyi.main:main
    - pytd = pytype.pytd.main:main
    - pytype = pytype.tools.analyze_project.main:main
    - pytype-single = pytype.single:main
    - pyxref = pytype.tools.xref.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11
    - pip
    - python
  run:
    - attrs
    - importlab >=0.5.1
    - ninja >=1.10.1
    - python
    - pyyaml >=3.11
    - six
    - typed-ast

test:
  imports:
    - pytype
    - pytype.overlays
  commands:
    - annotate-ast --help
    - merge-pyi --help
    - pytd --help
    - pytype --help
    - pytype-single --help
    - pyxref --help

about:
  home: https://google.github.io/pytype/
  summary: Python type inferencer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
