{% set name = "pytype" %}
{% set version = "2021.11.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/google/pytype/archive/refs/tags/{{ version }}.tar.gz
    sha256: ff9f5baec9c8fa9e8e04c7d7843aaf64e7e692d4693a2add78d23be064c98a40

  - url: https://github.com/google/googletest/archive/e82d320.tar.gz
    sha256: 7acdbac36f80ca68126c9112cf1e60132372aff81db7a14f08cb49e6e00af536
    folder: googletest
  - url: https://github.com/pybind/pybind11/archive/c16da99.tar.gz
    sha256: c90ada3976e1e261c49e14e18cec7645f7a744408bb258e60f0accc0171f0948
    folder: pybind11
  - url: https://github.com/python/typeshed/archive/8da23e0.tar.gz
    sha256: 318698194d9407be1753f972fcfc0616e19b0c9d9c5998ebd3e0e3e148ace611
    folder: typeshed

build:
  number: 1
  skip: true  # [py<36 or py>=310 or win]
  # no windows builds here: https://pypi.org/project/pytype/#files
  entry_points:
    - annotate-ast = pytype.tools.annotate_ast.main:main
    - merge-pyi = pytype.tools.merge_pyi.main:main
    - pytd = pytype.pytd.main:main
    - pytype = pytype.tools.analyze_project.main:main
    - pytype-single = pytype.single:main
    - pyxref = pytype.tools.xref.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - pip
    - python
  run:
    - attrs >=21.2.0
    - dataclasses
    - importlab >=0.6.1
    - ninja >=1.10.0
    - tabulate
    - toml
    - typed-ast >=1.5.0
    - libcst
    - pyyaml >=3.11
    - six
    - python
    
test:
  imports:
    - pytype
    - pytype.overlays
  commands:
    - annotate-ast --help
    - merge-pyi --help
    - pytd --help
    - pytype --help
    - pytype-single --help
    - pyxref --help

about:
  home: https://google.github.io/pytype/
  summary: Python type inferencer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
    - marcelotrevisani
